/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.dispositivo;

import dao.ContatoDAO;
import dao.MensagemDAO;
import dao.SQLiteBancoDAO;
import java.awt.Color;
import java.awt.Cursor;
import java.text.DecimalFormat;
import java.util.List;
import javax.swing.JOptionPane;
import model.Contato;
import model.Dispositivo;
import model.Mensagem;

/**
 *
 * @author BRUNA
 */
public class TelaDispositivoImportaBanco extends javax.swing.JFrame {
    private final Dispositivo dispositivo;
    private Thread threadMensagem;
    private Thread threadContato;

    /**
     * Creates new form TelaImportaBanco
     * 
     * @param dispositivo
     */
    public TelaDispositivoImportaBanco(Dispositivo dispositivo) {
        initComponents();
        
        this.dispositivo = dispositivo;
        preencheTextPaneDispositivo();
        
        labelContagemContato.setForeground(new Color(178, 34, 34));
        labelContagemContatoTotal.setForeground(new Color(34, 139, 34));
        labelContagemMensagem.setForeground(new Color(178, 34, 34));
        labelContagemMensagemTotal.setForeground(new Color(34, 139, 34));
    }

    private void preencheTextPaneDispositivo(){
        textPanelDispositivo.setText("Caso: "+this.dispositivo.getCaso().getDescricao()+" \n"
                                    +"Nome: "+this.dispositivo.getNome()+" \n"
                                    +"Fabricante: "+this.dispositivo.getFabricante()+" \n"
                                    +"Idioma: "+this.dispositivo.getIdioma()+" \n"
                                    +"Número do modelo: "+this.dispositivo.getNumero_modelo()+" \n"
                                    +"Modelo: "+this.dispositivo.getModelo()+" \n"
                                    +"Número da versão: "+this.dispositivo.getNumero_versao()+" \n"
                                    +"Versão do Android: "+this.dispositivo.getVersao_android()+" \n"
                                    +"Versão do Sistema: "+this.dispositivo.getVersao_sistema()+" \n"
                                    );
    }
    
    
   /* private void criaTabelas(){
        ContatoDAO contatoDAO = new ContatoDAO(dispositivo.getTabela_contato());
        contatoDAO.criaTabelaContato();
        MensagemDAO mensagemDAO = new MensagemDAO(this.dispositivo.getTabela_mensagem(), dispositivo.getTabela_contato());
        mensagemDAO.criaTabelaMensagem();
    }*/
    
    
    private List<Contato> contatosSQLite(){
        SQLiteBancoDAO sQLiteBancoDAO = new SQLiteBancoDAO(dispositivo.getDiretorio()+"\\wa.db");
        List<Contato> contatosSQLite = sQLiteBancoDAO.carregaTabelaContatoSQLite();
        
        DecimalFormat j = new DecimalFormat();
        labelContagemContatoTotal.setText(" de "+j.format(contatosSQLite.size()));
        
        return contatosSQLite;
    }
    
    
    private List<Mensagem> mensagensSQLite(){
        SQLiteBancoDAO sQLiteBancoDAO = new SQLiteBancoDAO(dispositivo.getDiretorio()+"\\msgstore.db");
        List<Mensagem> mensagensSQLite = sQLiteBancoDAO.carregaTabelaMensagensSQLite();
        
        DecimalFormat j = new DecimalFormat();
        labelContagemMensagemTotal.setText(" de "+j.format(mensagensSQLite.size()));
        
        return mensagensSQLite;
    }
    

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botaoIniciarImportacao = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textPanelDispositivo = new javax.swing.JTextPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        labelContagemContato = new javax.swing.JLabel();
        labelContagemContatoTotal = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        labelContagemMensagem = new javax.swing.JLabel();
        labelContagemMensagemTotal = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        botaoSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("IMPORTAÇÃO DOS DADOS");

        botaoIniciarImportacao.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        botaoIniciarImportacao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/iniciar.png"))); // NOI18N
        botaoIniciarImportacao.setText("Iniciar Importação");
        botaoIniciarImportacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoIniciarImportacaoActionPerformed(evt);
            }
        });

        textPanelDispositivo.setBackground(new java.awt.Color(240, 240, 240));
        textPanelDispositivo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        textPanelDispositivo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        textPanelDispositivo.setFocusable(false);
        jScrollPane1.setViewportView(textPanelDispositivo);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("CONTATOS:");

        labelContagemContato.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelContagemContato.setText("0");
        labelContagemContato.setPreferredSize(new java.awt.Dimension(50, 17));

        labelContagemContatoTotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelContagemContatoTotal.setText("de 0");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("MENSAGENS:");

        labelContagemMensagem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelContagemMensagem.setText("0");
        labelContagemMensagem.setPreferredSize(new java.awt.Dimension(50, 17));

        labelContagemMensagemTotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelContagemMensagemTotal.setText("de 0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelContagemMensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(labelContagemContato, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelContagemContatoTotal)
                    .addComponent(labelContagemMensagemTotal))
                .addContainerGap(172, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(labelContagemContato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelContagemContatoTotal))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(labelContagemMensagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelContagemMensagemTotal))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        botaoSair.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        botaoSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/sair.png"))); // NOI18N
        botaoSair.setText("Cancelar");
        botaoSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(botaoIniciarImportacao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botaoSair)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botaoSair, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(botaoIniciarImportacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoIniciarImportacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoIniciarImportacaoActionPerformed
        getContentPane().setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        
        threadMensagem = new Thread(){
            @Override
            public void run(){
                MensagemDAO mensagemDAO = new MensagemDAO(dispositivo.getTabela_mensagem(), dispositivo.getTabela_contato());
                List<Mensagem> mensagens = mensagensSQLite();
                
                double numero;
                DecimalFormat j = new DecimalFormat();
        
                for(int i = 0; i < mensagens.size(); i++){
                    mensagemDAO.insereMensagem(mensagens.get(i), dispositivo.getId());
                    numero = i+1;
                    
                    labelContagemMensagem.setText(j.format(numero));
                }
                
                labelContagemMensagem.setForeground(new Color(34, 139, 34));
                getContentPane().setCursor(Cursor.getDefaultCursor());
                JOptionPane.showMessageDialog(null, "Importação concluída!");
                dispose();
            }
        };
        
        
        threadContato = new Thread(){
            @Override
            public void run(){
                ContatoDAO contatoDAO = new ContatoDAO(dispositivo.getTabela_contato());
                List<Contato> contatos = contatosSQLite();
                boolean verifica = true;
                
                for(int i = 0; i < contatos.size(); i++){
                    verifica = contatoDAO.insereContato(contatos.get(i), dispositivo.getId());
                    
                    labelContagemContato.setText(String.valueOf(i+1));
                    
                    if(!verifica){
                        break;
                    }
                }
                
                labelContagemContato.setForeground(new Color(34, 139, 34));
                threadMensagem.start();
            }
        };
        
        threadContato.start();
       
    }//GEN-LAST:event_botaoIniciarImportacaoActionPerformed

    private void botaoSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSairActionPerformed
        if(threadContato != null){
            threadContato.interrupt();
        }
        if(threadMensagem != null){
            threadMensagem.interrupt();
        }
        
        JOptionPane.showMessageDialog(this, "Importação interrompida!");
        this.dispose();
    }//GEN-LAST:event_botaoSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaDispositivoImportaBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaDispositivoImportaBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaDispositivoImportaBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaDispositivoImportaBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaImportaBanco().setVisible(true);
            }
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaImportaBanco().setVisible(true);
            }
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaDispositivoImportaBanco().setVisible(true);
            }
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaDispositivoImportaBanco().setVisible(true);
            }
        });*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoIniciarImportacao;
    private javax.swing.JButton botaoSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelContagemContato;
    private javax.swing.JLabel labelContagemContatoTotal;
    private javax.swing.JLabel labelContagemMensagem;
    private javax.swing.JLabel labelContagemMensagemTotal;
    private javax.swing.JTextPane textPanelDispositivo;
    // End of variables declaration//GEN-END:variables
}