/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.caso;

import dao.CasoDAO;
import dao.UsuarioDAO;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import listmodel.JListModel;
import model.Acesso;
import model.Caso;
import model.Usuario;
import util.ConverteData;

/**
 *
 * @author BRUNA
 */
public class TelaNovoCaso extends javax.swing.JDialog {

    private List<Usuario> usuarios;
    private List<Usuario> usuariosSelecionados = new ArrayList<>();
    private final Usuario usuario;
    private Caso novoCaso;
    
    /**
     * Creates new form TelaNovoCaso
     * @param parent
     * @param modal
     * @param usuario
     */
    public TelaNovoCaso(java.awt.Frame parent, boolean modal, Usuario usuario) {
        super(parent, modal);
        initComponents();
        this.usuario = usuario;
        
        preencheDataCriacao();
        carregaJListContatos();
        jListUsuariosSelecionados.setModel(new JListModel(usuariosSelecionados));
    }

    private void preencheDataCriacao(){
        labelDataCriacao.setText(ConverteData.getStringDataAtual());
    }
    
    private void carregaJListContatos(){
        UsuarioDAO usuarioDAO = new UsuarioDAO();
        usuarios = usuarioDAO.pesquisaUsuarios(usuario.getId());
        jListUsuarios.setModel(new JListModel(usuarios));
    }
    
    private boolean verificaCamposPreenchidos(){
        if(campoDescricao.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Campo DESCRIÇÃO não preenchido!");
            return false;
        }
        if(campoNomeInvestigado.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Campo NOME DO INVESTIGADO não preenchido!");
            return false;
        }
        return true;
    }
        
    private void preencheObjetoCaso(){
        novoCaso = new Caso();
        novoCaso.setDescricao(campoDescricao.getText());
        novoCaso.setNome_investigado(campoNomeInvestigado.getText());
        novoCaso.setUsuario(usuario);
        novoCaso.setUsuarios_acesso(usuariosSelecionados);
    }
    
    private boolean criaPastaCaso(){
        File arquivoNovo = new File(usuario.getDiretorio_casos()+"\\"+novoCaso.getDescricao());
        arquivoNovo.mkdir();
        
        if(!arquivoNovo.exists()){
            JOptionPane.showMessageDialog(this, "Erro ao criar pasta do caso!");
            return false;
        }
        
        novoCaso.setDiretorio(arquivoNovo.getAbsolutePath());
        return true;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        campoDescricao = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        campoNomeInvestigado = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        labelDataCriacao = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListUsuarios = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListUsuariosSelecionados = new javax.swing.JList<>();
        botaoInsereUsuario = new javax.swing.JButton();
        botaoRemoveUsuario = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        botaoCriar = new javax.swing.JButton();
        botaoCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CRIAR NOVO CASO");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CRIAR NOVO CASO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(24, 62, 81))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Descrição:");

        campoDescricao.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Nome do investigado:");

        campoNomeInvestigado.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Data de criação:");

        labelDataCriacao.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelDataCriacao.setText("Data de criação:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Usuários que podem acessar:");

        jListUsuarios.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jListUsuarios);

        jListUsuariosSelecionados.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jListUsuariosSelecionados);

        botaoInsereUsuario.setText(">");
        botaoInsereUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoInsereUsuarioActionPerformed(evt);
            }
        });

        botaoRemoveUsuario.setText("<");
        botaoRemoveUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoRemoveUsuarioActionPerformed(evt);
            }
        });

        botaoCriar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        botaoCriar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/add.png"))); // NOI18N
        botaoCriar.setText("Criar");
        botaoCriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCriarActionPerformed(evt);
            }
        });

        botaoCancelar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        botaoCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/sair.png"))); // NOI18N
        botaoCancelar.setText("Cancelar");
        botaoCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoNomeInvestigado))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelDataCriacao))
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botaoInsereUsuario)
                            .addComponent(botaoRemoveUsuario))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(botaoCriar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botaoCancelar)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(campoDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoNomeInvestigado, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(labelDataCriacao))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel4)
                        .addGap(22, 22, 22)
                        .addComponent(botaoInsereUsuario)
                        .addGap(18, 18, 18)
                        .addComponent(botaoRemoveUsuario)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoCriar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoInsereUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoInsereUsuarioActionPerformed
        int in[] = jListUsuarios.getSelectedIndices();
        List<Usuario> listaAuxiliar = new ArrayList<>();
        
        if(in.length == 0){
            JOptionPane.showMessageDialog(this, "Nenhum usuário selecionado!");
        }
        else{
            for (int i = 0; i < in.length; i++) {
                usuariosSelecionados.add(usuarios.get(in[i]));
                listaAuxiliar.add(usuarios.get(in[i]));
            }
        
            for(Usuario u : listaAuxiliar){
                usuarios.remove(u);
            }
        
            jListUsuarios.setModel(new JListModel(usuarios));
            jListUsuariosSelecionados.setModel(new JListModel(usuariosSelecionados));
        }
    }//GEN-LAST:event_botaoInsereUsuarioActionPerformed

    private void botaoRemoveUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoRemoveUsuarioActionPerformed
        int in[] = jListUsuariosSelecionados.getSelectedIndices();
        List<Usuario> listaAuxiliar = new ArrayList<>();
        
        if(in.length == 0){
            JOptionPane.showMessageDialog(this, "Nenhum usuário selecionado!");
        }
        else{
            for (int i = 0; i < in.length; i++) {
                usuarios.add(usuariosSelecionados.get(in[i]));
                listaAuxiliar.add(usuariosSelecionados.get(in[i]));
            }
        
            for(Usuario u : listaAuxiliar){
                usuariosSelecionados.remove(u);
            }
            
            jListUsuarios.setModel(new JListModel(usuarios));
            jListUsuariosSelecionados.setModel(new JListModel(usuariosSelecionados));
        }
    }//GEN-LAST:event_botaoRemoveUsuarioActionPerformed

    private void botaoCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCriarActionPerformed
        CasoDAO casoDAO = new CasoDAO();

        if(casoDAO.verificaNomeCaso(campoDescricao.getText())){
            JOptionPane.showMessageDialog(this, "Já existe um caso com a descrição informada!");
        }
        else if(verificaCamposPreenchidos()){
            preencheObjetoCaso();
           
            if(criaPastaCaso()){
                if(casoDAO.inserir(novoCaso)){
                    casoDAO.relacionaCasoUsuario(Acesso.Criador, usuario.getId(), 0L); // usuario criador
                    
                    if(!usuariosSelecionados.isEmpty()){
                        for(Usuario usuarioSelecionado : usuariosSelecionados){
                            casoDAO.relacionaCasoUsuario(Acesso.Visualizar, usuarioSelecionado.getId(), 0L);
                        }
                    }
                    JOptionPane.showMessageDialog(this, "Caso criado!");
                    this.dispose();
                }
            }
        }
    }//GEN-LAST:event_botaoCriarActionPerformed

    private void botaoCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_botaoCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaNovoCaso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaNovoCaso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaNovoCaso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaNovoCaso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaNovoCaso dialog = new TelaNovoCaso(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCancelar;
    private javax.swing.JButton botaoCriar;
    private javax.swing.JButton botaoInsereUsuario;
    private javax.swing.JButton botaoRemoveUsuario;
    private javax.swing.JTextField campoDescricao;
    private javax.swing.JTextField campoNomeInvestigado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList<String> jListUsuarios;
    private javax.swing.JList<String> jListUsuariosSelecionados;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelDataCriacao;
    // End of variables declaration//GEN-END:variables
}
