/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.caso;

import dao.CasoDAO;
import dao.DispositivoDAO;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.util.List;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import model.Acesso;
import model.Caso;
import model.Dispositivo;
import model.Usuario;
import model.gerenciatela.GerenciaTelaCaso;
import tablemodel.TabelaModeloCaso;
import util.ConverteData;
import view.dispositivo.TelaDispositivoImportaBanco;
import view.dispositivo.TelaNovoDispositivo;
import view.dispositivo.TelaPrincipalDispositivo;
import view.usuario.TelaAlterarUsuario;
import view.usuario.TelaLogin;
import view.usuario.TelaSobre;

/**
 *
 * @author BRUNA
 */
public class TelaPrincipalCaso extends javax.swing.JFrame {
    private final Usuario usuarioLogado;
    private Dispositivo dispositivoSelecionado;
    private Caso casoSelecionado;
    private List<Caso> casos;
    private List<Caso> casosCompartilhados;
    private List<Dispositivo> dispositivos;
    private JPopupMenu menu;
    private JMenuItem itemAlterarCaso;
    private JMenuItem itemExcluirCaso;
    
    /**
     * Creates new form TelaPrincipalCaso
     * @param usuario
     */
    public TelaPrincipalCaso(Usuario usuario) {
        initComponents();
        this.usuarioLogado = usuario;
        this.setExtendedState(MAXIMIZED_BOTH);
        arvoreDispositivos.setVisible(false);
        
        gerenciaTela();
        preenchePainelInferior();
        preencheTabelasCasos();
        configuraJTable();
    }
    
    
    private void configuraJTable(){
        tabelaMeusCasos.setFont(new Font("Tahoma", Font.PLAIN, 14));
        tabelaMeusCasos.getTableHeader().setFont(new Font("Tahoma", Font.BOLD, 14));
        tabelaMeusCasos.getTableHeader().setForeground(new Color(255,149,40));
        tabelaMeusCasos.setRowHeight(25);
        tabelaCasosCompartilhados.setFont(new Font("Tahoma", Font.PLAIN, 14));
        tabelaCasosCompartilhados.getTableHeader().setFont(new Font("Tahoma", Font.BOLD, 14));
        tabelaCasosCompartilhados.getTableHeader().setForeground(new Color(255,149,40));
        tabelaCasosCompartilhados.setRowHeight(25);
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelDispositivos = new javax.swing.JPanel();
        scrollPaneArvoreDispositivos = new javax.swing.JScrollPane();
        arvoreDispositivos = new javax.swing.JTree();
        botaoAbrir = new javax.swing.JButton();
        botaoNovo = new javax.swing.JButton();
        painelInferior = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        labelUsuario = new javax.swing.JLabel();
        labelData = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        painelCasos = new javax.swing.JPanel();
        scrollPaneTabelaCasos = new javax.swing.JScrollPane();
        tabelaMeusCasos = new javax.swing.JTable();
        painelCasosCompartilhados = new javax.swing.JPanel();
        scrollPaneTabelaCasosCompartilhados = new javax.swing.JScrollPane();
        tabelaCasosCompartilhados = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        itemNovoCaso = new javax.swing.JMenuItem();
        itemAlterar = new javax.swing.JMenuItem();
        itemExcluir = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        menuConfigurar = new javax.swing.JMenu();
        botaoAlterarDados = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        itemSobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LISTA DE CASOS");
        setBackground(new java.awt.Color(255, 255, 255));
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        painelDispositivos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DISPOSITIVOS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(24, 62, 81))); // NOI18N

        scrollPaneArvoreDispositivos.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        arvoreDispositivos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        arvoreDispositivos.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                arvoreDispositivosValueChanged(evt);
            }
        });
        scrollPaneArvoreDispositivos.setViewportView(arvoreDispositivos);

        botaoAbrir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        botaoAbrir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/abrir.png"))); // NOI18N
        botaoAbrir.setText("ABRIR");
        botaoAbrir.setPreferredSize(new java.awt.Dimension(81, 30));
        botaoAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAbrirActionPerformed(evt);
            }
        });

        botaoNovo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        botaoNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/add.png"))); // NOI18N
        botaoNovo.setText("NOVO");
        botaoNovo.setPreferredSize(new java.awt.Dimension(81, 30));
        botaoNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoNovoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelDispositivosLayout = new javax.swing.GroupLayout(painelDispositivos);
        painelDispositivos.setLayout(painelDispositivosLayout);
        painelDispositivosLayout.setHorizontalGroup(
            painelDispositivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDispositivosLayout.createSequentialGroup()
                .addGroup(painelDispositivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelDispositivosLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(scrollPaneArvoreDispositivos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(painelDispositivosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(botaoAbrir, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addComponent(botaoNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        painelDispositivosLayout.setVerticalGroup(
            painelDispositivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDispositivosLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(scrollPaneArvoreDispositivos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(painelDispositivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoAbrir, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        painelInferior.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("USUÁRIO:");

        labelUsuario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelUsuario.setText("usuario");

        labelData.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelData.setText("HOJE:");

        javax.swing.GroupLayout painelInferiorLayout = new javax.swing.GroupLayout(painelInferior);
        painelInferior.setLayout(painelInferiorLayout);
        painelInferiorLayout.setHorizontalGroup(
            painelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelInferiorLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelData)
                .addContainerGap())
        );
        painelInferiorLayout.setVerticalGroup(
            painelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelInferiorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(labelUsuario)
                    .addComponent(labelData))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.setForeground(new java.awt.Color(24, 62, 81));
        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        scrollPaneTabelaCasos.setBackground(new java.awt.Color(255, 255, 255));

        tabelaMeusCasos.setForeground(new java.awt.Color(51, 51, 51));
        tabelaMeusCasos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelaMeusCasos.setGridColor(new java.awt.Color(204, 204, 204));
        tabelaMeusCasos.setSelectionBackground(new java.awt.Color(40, 101, 132));
        tabelaMeusCasos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tabelaMeusCasos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMeusCasosMouseClicked(evt);
            }
        });
        scrollPaneTabelaCasos.setViewportView(tabelaMeusCasos);

        painelCasos.add(scrollPaneTabelaCasos);

        jTabbedPane1.addTab("MEUS CASOS", null, painelCasos, "");

        scrollPaneTabelaCasosCompartilhados.setBackground(new java.awt.Color(255, 255, 255));

        tabelaCasosCompartilhados.setForeground(new java.awt.Color(51, 51, 51));
        tabelaCasosCompartilhados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelaCasosCompartilhados.setGridColor(new java.awt.Color(204, 204, 204));
        tabelaCasosCompartilhados.setSelectionBackground(new java.awt.Color(40, 101, 132));
        tabelaCasosCompartilhados.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tabelaCasosCompartilhados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaCasosCompartilhadosMouseClicked(evt);
            }
        });
        scrollPaneTabelaCasosCompartilhados.setViewportView(tabelaCasosCompartilhados);

        painelCasosCompartilhados.add(scrollPaneTabelaCasosCompartilhados);

        jTabbedPane1.addTab("CASOS COMPARTILHADOS", painelCasosCompartilhados);

        jMenuBar1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jMenu1.setText("Caso");

        itemNovoCaso.setText("Novo");
        itemNovoCaso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemNovoCasoActionPerformed(evt);
            }
        });
        jMenu1.add(itemNovoCaso);

        itemAlterar.setText("Alterar");
        itemAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAlterarActionPerformed(evt);
            }
        });
        jMenu1.add(itemAlterar);

        itemExcluir.setText("Excluir");
        itemExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemExcluirActionPerformed(evt);
            }
        });
        jMenu1.add(itemExcluir);

        jMenuItem1.setText("Sair");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        menuConfigurar.setText("Configurar");

        botaoAlterarDados.setText("Alterar Dados");
        botaoAlterarDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAlterarDadosActionPerformed(evt);
            }
        });
        menuConfigurar.add(botaoAlterarDados);

        jMenuBar1.add(menuConfigurar);

        jMenu2.setText("Ajuda");

        itemSobre.setText("Sobre");
        itemSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSobreActionPerformed(evt);
            }
        });
        jMenu2.add(itemSobre);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelInferior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(painelDispositivos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTabbedPane1)
                    .addComponent(painelDispositivos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(painelInferior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAbrirActionPerformed
        if(dispositivoSelecionado == null){
            JOptionPane.showMessageDialog(this, "Selecione um dispositivo!");
        }
        else{
            DispositivoDAO dispositivoDAO = new DispositivoDAO();
            
            if(dispositivoDAO.verificaImportacaoDispositivo(dispositivoSelecionado.getTabela_contato()) > 0){
                new TelaPrincipalDispositivo(this, false, dispositivoSelecionado).setVisible(true);
            }
            else{
                new TelaDispositivoImportaBanco(dispositivoSelecionado).setVisible(true);
            }
        }
    }//GEN-LAST:event_botaoAbrirActionPerformed

    private void arvoreDispositivosValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_arvoreDispositivosValueChanged
        if(!evt.getPath().getLastPathComponent().toString().equals(casoSelecionado.getDescricao())){
            DispositivoDAO dispositivoDAO = new DispositivoDAO();
            dispositivoSelecionado = dispositivoDAO.pesquisaDispositivoPorNome(evt.getPath().getLastPathComponent().toString(), casoSelecionado);
        }
    }//GEN-LAST:event_arvoreDispositivosValueChanged

    private void tabelaMeusCasosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMeusCasosMouseClicked
        if(evt.getClickCount() > 1){
            this.casoSelecionado = casos.get(tabelaMeusCasos.getSelectedRow());
            carregaListaDispositivos();
            carregaJTreeDispositivos();
            arvoreDispositivos.setVisible(true);
        }
        
        else if(evt.getButton() == evt.BUTTON3){
            tabelaMeusCasos.setRowSelectionInterval(tabelaMeusCasos.rowAtPoint(evt.getPoint()), tabelaMeusCasos.rowAtPoint(evt.getPoint()));
            casoSelecionado = casos.get(tabelaMeusCasos.rowAtPoint(evt.getPoint()));
            carregaMenu();
            menu.show(tabelaMeusCasos, evt.getX(), evt.getY());
            menu.setVisible(true);
            menu.setLocation(evt.getLocationOnScreen());
        }
    }//GEN-LAST:event_tabelaMeusCasosMouseClicked

    private void botaoNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoNovoActionPerformed
        if(casoSelecionado == null){
            JOptionPane.showMessageDialog(this, "É necessário selecionar um caso!");
        }
        else{
            new TelaNovoDispositivo(this, true, casoSelecionado).setVisible(true);
        }
    }//GEN-LAST:event_botaoNovoActionPerformed

    private void itemNovoCasoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemNovoCasoActionPerformed
        new TelaNovoCaso(this, true, usuarioLogado).setVisible(true);
    }//GEN-LAST:event_itemNovoCasoActionPerformed

    private void tabelaCasosCompartilhadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaCasosCompartilhadosMouseClicked
        if(evt.getClickCount() > 1){
            this.casoSelecionado = casos.get(tabelaCasosCompartilhados.getSelectedRow());
            carregaListaDispositivos();
            carregaJTreeDispositivos();
            arvoreDispositivos.setVisible(true);
        }
    }//GEN-LAST:event_tabelaCasosCompartilhadosMouseClicked

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        preencheTabelasCasos();
        
        if(casoSelecionado != null){
            carregaListaDispositivos();
            carregaJTreeDispositivos();
        }
        
    }//GEN-LAST:event_formWindowGainedFocus

    private void botaoAlterarDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAlterarDadosActionPerformed
        new TelaAlterarUsuario(this, true, usuarioLogado).setVisible(true);
    }//GEN-LAST:event_botaoAlterarDadosActionPerformed

    private void itemExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemExcluirActionPerformed
        excluirCaso();
    }//GEN-LAST:event_itemExcluirActionPerformed

    private void itemAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAlterarActionPerformed
        alterarCaso();
    }//GEN-LAST:event_itemAlterarActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new TelaLogin().setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void itemSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSobreActionPerformed
         new TelaSobre().setVisible(true);
    }//GEN-LAST:event_itemSobreActionPerformed

    
    private void gerenciaTela() {
        GerenciaTelaCaso gt = new GerenciaTelaCaso();
        this.setSize(gt.getFramePrincipalCaso());
        painelCasos.setPreferredSize(gt.getPainelCasos());
        painelCasosCompartilhados.setPreferredSize(gt.getPainelCasos());
        painelDispositivos.setPreferredSize(gt.getPainelDispositivos());
        painelInferior.setPreferredSize(gt.getPainelInferior());
        scrollPaneTabelaCasos.setPreferredSize(gt.getTabelaCasos());
        scrollPaneTabelaCasosCompartilhados.setPreferredSize(gt.getTabelaCasos());
        scrollPaneArvoreDispositivos.setPreferredSize(gt.getArvoreDispositivos());
    }
    
    
    private void preenchePainelInferior(){
        labelUsuario.setText(usuarioLogado.getNome());
        labelData.setText("HOJE: "+ConverteData.getStringDataAtual());
    }
    
    
    private void carregaJTreeDispositivos(){
        DefaultMutableTreeNode titulo = new DefaultMutableTreeNode(casoSelecionado.getDescricao());

        if(dispositivos.isEmpty()){
            DefaultMutableTreeNode dispositivo[] = new DefaultMutableTreeNode[1];
            dispositivo[0] = new DefaultMutableTreeNode("Sem dispositivos");
            titulo.add(dispositivo[0]);
        }
        else{
            for (int i = 0; i < dispositivos.size(); i++) {
                DefaultMutableTreeNode dispositivo[] = new DefaultMutableTreeNode[dispositivos.size()];
                dispositivo[i] = new DefaultMutableTreeNode(dispositivos.get(i));
                titulo.add(dispositivo[i]);
            }
        }
        
        arvoreDispositivos.setModel(new DefaultTreeModel(titulo));
    }
    
    
    private void preencheTabelasCasos(){
        CasoDAO casoDAO = new CasoDAO();
        casos = casoDAO.pesquisaListaCasos(usuarioLogado, Acesso.Criador);
        casosCompartilhados = casoDAO.pesquisaListaCasos(usuarioLogado, Acesso.Visualizar);
        tabelaMeusCasos.setModel(new TabelaModeloCaso(casos));
        tabelaCasosCompartilhados.setModel(new TabelaModeloCaso(casosCompartilhados));
    }
    
    
    private void carregaListaDispositivos(){
        DispositivoDAO dispositivoDAO = new DispositivoDAO();
        dispositivos = dispositivoDAO.dispositivosPorCaso(casoSelecionado);
    }
    
    
    private void alterarCaso(){
        if(casoSelecionado == null){
            JOptionPane.showMessageDialog(this, "Selecione um caso!");
        }
        else{
            System.out.println(casoSelecionado.getId());
            new TelaAlterarCaso(this, true, casoSelecionado, usuarioLogado).setVisible(true);
        }
    }
    
    private void excluirCaso(){
        if(casoSelecionado == null){
            JOptionPane.showMessageDialog(this, "Selecione um caso!");
        }
        else{
            int resposta = JOptionPane.showConfirmDialog(this, "Tem certeza que deseja excluir o caso: "+casoSelecionado.getDescricao(), "EXCLUIR CASO", JOptionPane.YES_NO_CANCEL_OPTION);
            
            if(resposta == 0){
                DispositivoDAO dispositivoDAO = new DispositivoDAO();
                List<Dispositivo> dispositivosExcluir = dispositivoDAO.dispositivosPorCaso(casoSelecionado);
                
                for(Dispositivo dispositivo : dispositivosExcluir){
                    dispositivoDAO.excluir(dispositivo);
                    File file = new File(dispositivo.getDiretorio());
                    file.delete();
                }
                
                CasoDAO casoDAO = new CasoDAO();
                if(casoDAO.excluir(casoSelecionado)){
                    File file = new File(casoSelecionado.getDiretorio());
                    file.delete();
                    
                    casoSelecionado = null;  
                    JOptionPane.showMessageDialog(this, "Caso excluído!");
                }
            }
        }
    }
    
    
    
    private void carregaMenu(){
        menu = new JPopupMenu();
        itemAlterarCaso = new JMenuItem("Alterar");
        itemExcluirCaso = new JMenuItem("Excluir");
        menu.add(itemAlterar);
        menu.add(itemExcluir);
        tabelaMeusCasos.add(menu);
        
        itemAlterarCaso.addActionListener(new ActionListener(){ 
            @Override
            public void actionPerformed(ActionEvent e) {
                alterarCaso();
            }
        });
        
        itemExcluirCaso.addActionListener(new ActionListener(){ 
            @Override
            public void actionPerformed(ActionEvent e) {
                excluirCaso();
            }
        });
    }
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalCaso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalCaso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalCaso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalCaso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipalCaso().setVisible(true);
            }
        });*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTree arvoreDispositivos;
    private javax.swing.JButton botaoAbrir;
    private javax.swing.JMenuItem botaoAlterarDados;
    private javax.swing.JButton botaoNovo;
    private javax.swing.JMenuItem itemAlterar;
    private javax.swing.JMenuItem itemExcluir;
    private javax.swing.JMenuItem itemNovoCaso;
    private javax.swing.JMenuItem itemSobre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel labelData;
    private javax.swing.JLabel labelUsuario;
    private javax.swing.JMenu menuConfigurar;
    private javax.swing.JPanel painelCasos;
    private javax.swing.JPanel painelCasosCompartilhados;
    private javax.swing.JPanel painelDispositivos;
    private javax.swing.JPanel painelInferior;
    private javax.swing.JScrollPane scrollPaneArvoreDispositivos;
    private javax.swing.JScrollPane scrollPaneTabelaCasos;
    private javax.swing.JScrollPane scrollPaneTabelaCasosCompartilhados;
    private javax.swing.JTable tabelaCasosCompartilhados;
    private javax.swing.JTable tabelaMeusCasos;
    // End of variables declaration//GEN-END:variables
}
